#!/bin/bash

reponame=curves
user=UlfNorell
repo=git@github.com:${user}/${reponame}.git

cd /tmp
git clone $repo
cd $reponame
git checkout gh-pages
git merge master -m "[auto] merged master into gh-pages"
make clean
make

if [ "`git status --porcelain`" != "" ]; then
  echo "Updates:"
  git status --porcelain
  git add --all
  git commit -m "[auto] updated gh-pages"
  git push
else
  echo "No changes!"
  # Still push the merge (if there was one)
  git push
fi

cd ..
rm -rf $reponame
